### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by pparthenhs** [sharplab/spring-security-webauthn#12]
Hello everyone, 

Congratulation, for this repository and your work on it. 

I face a problem with the `build`
![image](https://user-images.githubusercontent.com/9752042/58897333-b81a6c80-8700-11e9-86c1-0f1a587210f0.png)

I face, also, another problem with the quick start command `./gradlew spring-security-webauthn-samples/javaconfig/webauthn/spa:bootRun` 
![image](https://user-images.githubusercontent.com/9752042/58897413-ed26bf00-8700-11e9-9ee6-480b6d5870ff.png)

**Comment by ynojima** [comment]
Could you paste full log of the build?

Sorry, quick start command has changed.
Please execute the following:
```
./gradlew samples:javaconfig:webauthn:spa:bootRun
```

**Comment by pparthenhs** [comment]
Using your command it worked!!
