### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by jajmo** [sharplab/spring-security-webauthn#3]
Firefox does support WebAuthN login, and it has for quite some time now. There's no need to not allow the user to authenticate if they're using Firefox. Maybe just a version check instead.

**Comment by ynojima** [comment]
It seems you used "Device Login" button in login page. It is for "Password-less login" which is not supported by Firefox's WebAuthn implementation.

Could you try "Login" button in login page? If you succeed to login with password, You will be redirected to authenticator login page, where you will be asked to login with authenticator as second factor.

**Comment by ynojima** [comment]
If you'd like to test "Password-less login", try with Microsoft Edge bundled with Windows 10 October 2018 update.

Here is a document about sample application: https://sharplab.github.io/spring-security-webauthn/en/#sample-application

**Comment by jajmo** [comment]
Firefox does support passwordless login. I have another webauthn demo site that works perfectly with firefox using passwordless login.

**Comment by ynojima** [comment]
No, it doesn't. Here is a post from J.C. Jones. He is a developer of Firefox's WebAuthn support.
> Firefox's implementation only implements support for external USB "U2F" tokens today, and only on Desktop versions.
https://groups.google.com/a/fidoalliance.org/forum/#!topic/fido-dev/a0FQGCKWsj0

"U2F" token is for second factor. It proves the possession of authenticator, but doesn't verifies user by anything he knows ( like PIN) or he is ( like fingerprint).
Comparing to FIDO U2F, Verifying user is a major characteristics of FIDO2 standard.
Only FIDO2 authenticator ( or internal authenticator like Windows Hello) supports password-less login.

**Comment by jajmo** [comment]
That post is from January. It is now December, and Firefox is on version 63. J.C. clearly states WebAuthN (passwordless login) was due to ship in Firefox 60. Which it did. If you go to `about:config` in Firefox and search for `webauthn`, you can see that the option is enabled, indicating that passwordless login is enabled.

If that isn't enough proof, go to https://webauthn.io/ and test it for yourself.

**Comment by ynojima** [comment]
I've answered in https://github.com/sharplab/spring-security-webauthn/issues/2#issuecomment-443798591

**Comment by ynojima** [comment]
Since it looks like we are on the same page now, I'll go ahead and close this. If you still have an issue, please reopen.
